<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.5">
  <POU Name="MAIN" Id="{9753ee2a-e609-4081-882e-52e8c65681cc}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	SystemFunktionen:SystemFunktionen;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[DatenRangieren();		// Nicht löschen
SystemFunktionen();		// Nicht löschen]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="3" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>